--
-- PostgreSQL database dump
--

\restrict t7wKwq62XqLOTf4SW7R8YwOncAHbh9ggfzI75Cta2DTxywQdRiIJnFqZDaezbtf

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: programaEducativo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."programaEducativo" (
    "idPrograma" smallint NOT NULL,
    nombre character varying(100) NOT NULL,
    estatus bit(1) NOT NULL
);


--
-- Name: programaEducativo_idPrograma_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."programaEducativo_idPrograma_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 32767
    CACHE 1;


--
-- Name: programaEducativo_idPrograma_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."programaEducativo_idPrograma_seq" OWNED BY public."programaEducativo"."idPrograma";


--
-- Name: programaEducativo_idPrograma_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."programaEducativo" ALTER COLUMN "idPrograma" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."programaEducativo_idPrograma_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rol (
    idrol smallint NOT NULL,
    nombre character varying(50) NOT NULL,
    estatus bit(1) NOT NULL
);


--
-- Name: rol_idrol_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.rol_idrol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 32767
    CACHE 1;


--
-- Name: rol_idrol_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.rol_idrol_seq OWNED BY public.rol.idrol;


--
-- Name: rol_idrol_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rol ALTER COLUMN idrol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_idrol_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipoUsuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."tipoUsuario" (
    "idTipo" smallint NOT NULL,
    nombre character varying(50) NOT NULL,
    estatus bit(1) NOT NULL
);


--
-- Name: tipoUsuario_idTipo_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."tipoUsuario_idTipo_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 32767
    CACHE 1;


--
-- Name: tipoUsuario_idTipo_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."tipoUsuario_idTipo_seq" OWNED BY public."tipoUsuario"."idTipo";


--
-- Name: tipoUsuario_idTipo_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."tipoUsuario" ALTER COLUMN "idTipo" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."tipoUsuario_idTipo_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario (
    "idUsuario" integer NOT NULL,
    nombre character varying(50) NOT NULL,
    "apellidoPaterno" character varying(50) NOT NULL,
    "apellidoMaterno" character varying(50),
    "claveUsuario" character varying(10) NOT NULL,
    email character varying(255) NOT NULL,
    telefono character varying(10),
    username character varying(30) NOT NULL,
    password text NOT NULL,
    estatus bit(1) NOT NULL,
    "idRol" smallint NOT NULL,
    "idTipoUsuario" smallint NOT NULL,
    "idProgramaEducativo" smallint NOT NULL,
    "tiempoCreacion" timestamp(6) without time zone,
    "tempoActualizacion" timestamp(6) without time zone
);


--
-- Name: usuarioFullInfo; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public."usuarioFullInfo" AS
 SELECT u."idUsuario",
    u.nombre,
    u."apellidoPaterno",
    u."apellidoMaterno",
    u."claveUsuario",
    u.email,
    u.telefono,
    u.username,
    u.password,
    u.estatus,
    u."idRol",
    r.nombre AS rol,
    u."idTipoUsuario",
    tu.nombre AS "tipoUsuario",
    u."idProgramaEducativo",
    pe.nombre AS "programaEducativo",
    u."tiempoCreacion",
    u."tempoActualizacion"
   FROM (((public.usuario u
     JOIN public.rol r ON ((r.idrol = u."idRol")))
     JOIN public."tipoUsuario" tu ON ((tu."idTipo" = u."idTipoUsuario")))
     JOIN public."programaEducativo" pe ON ((pe."idPrograma" = u."idProgramaEducativo")));


--
-- Name: usuario_idUsuario_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public."usuario_idUsuario_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1;


--
-- Name: usuario_idUsuario_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public."usuario_idUsuario_seq" OWNED BY public.usuario."idUsuario";


--
-- Name: usuario_idUsuario_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario ALTER COLUMN "idUsuario" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."usuario_idUsuario_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: programaEducativo; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."programaEducativo" ("idPrograma", nombre, estatus) FROM stdin;
1	Lic. en Ingeniería de Software	1
2	Lic. en Ingeniería de Ciberseguridade Infraestructura de Cómputo	1
3	Lic. en Ingeniería en Sistemas y Tecnologías de la Información	1
4	Lic. en Ingeniería en Ciencia de Datos	1
5	Maestría en Sistemas Interactivos Centrados en el Usuario	1
6	Doctorado en Ciencias de la Computación (DCC)	1
7	Especialización en Métodos Estadísticos	1
\.


--
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.rol (idrol, nombre, estatus) FROM stdin;
1	administrador	1
2	invitado	1
\.


--
-- Data for Name: tipoUsuario; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."tipoUsuario" ("idTipo", nombre, estatus) FROM stdin;
1	Docente	1
2	Administrativo	1
3	Alumno	1
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuario ("idUsuario", nombre, "apellidoPaterno", "apellidoMaterno", "claveUsuario", email, telefono, username, password, estatus, "idRol", "idTipoUsuario", "idProgramaEducativo", "tiempoCreacion", "tempoActualizacion") FROM stdin;
2	Michell	Cid	Rodriguez	fei	michell@uv.mx	2281002030	michell	12345	1	1	1	3	2026-06-16 20:20:00	\N
1	Administrador	fei	\N	admin	admin@example.com	\N	admin	$2y$10$nqbsFHzFvT2F71SY32CsReoQCXMcr1kATlSqb8ZBKs8QYopTlYhJy	1	1	1	3	2026-05-25 19:30:55	\N
\.



INSERT INTO public.usuario
("idUsuario", nombre, "apellidoPaterno", "apellidoMaterno", "claveUsuario", email, telefono, username, password, estatus, "idRol", "idTipoUsuario", "idProgramaEducativo", "tiempoCreacion", "tempoActualizacion")
VALUES
-- Usuario activo con 4 vehículos
(3, 'Carlos', 'Ramirez', 'Lopez', 'CARLOS01', 'carlos@uv.mx', '2281111111', 'carlos', '12345', B'1', 2, 3, 3, NOW(), NULL),

-- Usuario activo con 2 vehículos
(4, 'Ana', 'Torres', 'Mendez', 'ANA02', 'ana@uv.mx', '2282222222', 'ana', '12345', B'1', 2, 3, 4, NOW(), NULL),

-- Usuario desactivado
(5, 'Luis', 'Garcia', 'Perez', 'LUIS03', 'luis@uv.mx', '2283333333', 'luis', '12345', B'0', 2, 3, 3, NOW(), NOW()),

-- Otro usuario desactivado
(6, 'Mariana', 'Hernandez', 'Soto', 'MARI04', 'mariana@uv.mx', '2284444444', 'mariana', '12345', B'0', 1, 2, 1, NOW(), NOW()),

-- Otro usuario activo de rol administrador
(7, 'Roberto', 'Diaz', 'Cruz', 'ROBER05', 'roberto@uv.mx', '2285555555', 'roberto', '12345', B'1', 1, 1, 3, NOW(), NULL);


SELECT setval('public."usuario_idUsuario_seq1"', 7, true);

--
-- Name: programaEducativo_idPrograma_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."programaEducativo_idPrograma_seq"', 7, true);


--
-- Name: programaEducativo_idPrograma_seq1; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."programaEducativo_idPrograma_seq1"', 1, false);


--
-- Name: rol_idrol_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.rol_idrol_seq', 2, true);


--
-- Name: rol_idrol_seq1; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.rol_idrol_seq1', 1, false);


--
-- Name: tipoUsuario_idTipo_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."tipoUsuario_idTipo_seq"', 3, true);


--
-- Name: tipoUsuario_idTipo_seq1; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."tipoUsuario_idTipo_seq1"', 1, false);


--
-- Name: usuario_idUsuario_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."usuario_idUsuario_seq"', 1, true);


--
-- Name: usuario_idUsuario_seq1; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."usuario_idUsuario_seq1"', 1, false);


--
-- Name: programaEducativo programaEducativo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."programaEducativo"
    ADD CONSTRAINT "programaEducativo_pkey" PRIMARY KEY ("idPrograma");


--
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (idrol);


--
-- Name: tipoUsuario tipoUsuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."tipoUsuario"
    ADD CONSTRAINT "tipoUsuario_pkey" PRIMARY KEY ("idTipo");


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY ("idUsuario");


--
-- Name: usuario usuario_idProgramaEducativo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT "usuario_idProgramaEducativo_fkey" FOREIGN KEY ("idProgramaEducativo") REFERENCES public."programaEducativo"("idPrograma");


--
-- Name: usuario usuario_idRol_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT "usuario_idRol_fkey" FOREIGN KEY ("idRol") REFERENCES public.rol(idrol);


--
-- Name: usuario usuario_idTipoUsuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT "usuario_idTipoUsuario_fkey" FOREIGN KEY ("idTipoUsuario") REFERENCES public."tipoUsuario"("idTipo");


--
-- PostgreSQL database dump complete
--

\unrestrict t7wKwq62XqLOTf4SW7R8YwOncAHbh9ggfzI75Cta2DTxywQdRiIJnFqZDaezbtf

