spring.application.name=auth-service
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/sicaeUsuario
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.configuration.map-underscore-to-camel-case=false

jwt.secret=clave_secreta_sicae_auth_service
jwt.expiration=3600000
