services:
    
    
    
    bd-estacionamiento:
        image: mysql:8
        container_name: bd-estacionamiento
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: sicaeParking
            MYSQL_USER: usuarioServidor3
            MYSQL_PASSWORD: S3rv1d0r3
            MYSQL_ROOT_PASSWORD: c0ntr4s3ñ4ROOT
            
        volumes:
            - datos_estacionamiento:/var/lib/mysql
            - ../databases/BD/MySQL/sicaeestacionamiento.sql:/docker-entrypoint-initdb.d/sicaeestacionamiento.sql
        networks:
            - sicae_network



    
    
    
    
    parking-service:
        build: ../parking-service/parking-service
        container_name: parking-service 
        ports:
            - "8083:8083"
        environment:
            SERVER_PORT: 8083
            SPRING_DATASOURCE_URL: jdbc:mysql://bd-estacionamiento:3306/sicaeParking
            SPRING_DATASOURCE_USERNAME: usuarioServidor3
            SPRING_DATASOURCE_PASSWORD: S3rv1d0r3
            JWT_SECRET: secretkey
            AUTH_SERVICE_URL: http://auth-service:8080
            USER_SERVICE_URL: http://user-service:8081/
            VEHICLE_SERVICE_URL: http://vehicle-service:8082/api/vehiculos/
        depends_on:
            - bd-estacionamiento 
        
        networks:
            - sicae_network







volumes:
        datos_estacionamiento:

networks:
        sicae_network:
            external: true  